name: PHPUnit Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v6

      - name: PHPUnit test with PHP 8.0
        uses: php-actions/phpunit@v3
        with:
          bootstrap: tests/bootstrap.php
          configuration: phpunit.xml
          php_version: 8.0
